apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: backend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}-backend:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          resources:
            requests:
              cpu: {{ .Values.backend.cpuRequest }}
              memory: {{ .Values.backend.memoryRequest }}
